name: Go Security Scans

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  govulncheck:
    name: Go Vulnerability Check (govulncheck)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run govulncheck
        run: govulncheck -show verbose ./...

  golangci:
    name: Lint Check (golangci-lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --timeout 5m --config .golangci.yml

  gosec:
    name: Static Code Analysis (gosec)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run gosec
        run: gosec ./...

  gitleaks:
    name: Secret Scan (gitleaks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git -v

  trivy:
    name: Dependency Vulnerability Scan (Trivy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy (Go Modules Scan)
        run: |
          trivy fs --scanners vuln --vuln-type library --severity LOW,MEDIUM,HIGH,CRITICAL --exit-code 1 --no-progress .
  
  auto-pr:
    name: Create Pull Request if all checks pass
    needs:
      - govulncheck
      - golangci
      - gosec
      - gitleaks
      - trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: automated security updates"
          title: "chore: security scan passed ✅ - automated PR"
          body: |
            All security checks have passed. This PR was automatically generated.
          branch: "auto/security-scan-passed"